---
- name: Configure APT sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root

- name: update apt cache and upgrade dist
  apt:
    upgrade: yes
    update_cache: yes

- name: install required packages
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - '{{ common_packages }}'

- name: install python pip module
  easy_install:
    name: pip
