---
- hosts: '{{ host }}'
  become: yes
  environment:
    http_proxy: 'http://localhost:3128'
    https_proxy: 'http://localhost:3128'
    ftp_proxy: 'http://localhost:3128'

  roles:
    - zabbix-agent
