---
- hosts: '{{ host }}'
  gather_facts: no
  become: yes

  vars_prompt:
    - name: 'username'
      prompt: 'Enter username'
      private: no

  tasks:
    - name: delete user
      user: name='{{ username }}' state=absent

    - name: revoke sudo privileges (if granted)
      lineinfile: dest=/etc/sudoers state=absent regexp='^{{ username }} ALL\=' validate='visudo -cf %s'
