---
- name: Add docker GPG key
  apt_key:
    keyserver: "hkp://pgp.mit.edu:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Configure APT sources
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root

- name: Install docker
  apt:
    name: docker-engine
    update_cache: yes
    cache_valid_time: 0
